### ISSUE TITLE
Why isn't ExecuteFunction called ExecuteProcess?

### ISSUE THREAD

**Issue by paulsimongb** [IBM/paxapi#37]

**Comment by tedphillips** [comment]
quirks of the heritage mostly. creating a better-named alternative doesn't let us exit the existing name (as that's a breaking api change), so i'm not particularly confident it would change.

we do try to name things well, of course.

entry points offered on the automation object (as opposed to reporting) are generally intended to be datasource-type agnostic (instead of PA-specific), and thus tend to have more neutral names. at some point it was in the running to do something for BI/CA/other based systems as well & predates some particular alignments with PA.

if we offer a better version with a different signature for some reason, they'll be an opportunity to consider the name going forward I'll try to make sure this is raised.
